import Script from 'next/script'
import ClarityInit from '../components/ClarityInit'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: '/img/static/favicon.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <ClarityInit />
        {children}
      </body>
    </html>
  )
}
